name: PHP-QA
on: [push]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nathanheffley/laravel-phpunit-action@master

name: PHP Linting
on: pull_request

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: michaelw90/PHP-Lint@master
