name: PHP-QA
on: [push]

jobs:
  PHPunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PHPunit
        uses: nathanheffley/laravel-phpunit-action@master

  PHPlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: PHPlint
        uses: michaelw90/PHP-Lint@master

  PHPcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master
        with:
          dir: app/
          cli: --standard=PSR1,PSR2,PSR12,Zend

