name: PHP-QA
on: [push]

jobs:
  PHPunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node_modules
      - run: composer install
      - name: run PHPunit
      - run: vendor/bin/phpunit
      #- uses: nathanheffley/laravel-phpunit-action@master

