name: TEST
on: [push]

jobs:
  PHPunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Generate key
        run: php artisan key:generate
      - name: Run PHPunit
        run: vendor/bin/phpunit

  PHPlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run PHPlint
        run: vendor/bin/phplint --no-cache

  PHPcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install
      - name: Run PHP CodeStyle (phpcs)
        run: vendor/bin/phpcs --standard=PSR1,PSR2,PSR12,Zend app/

